### ISSUE TITLE
Oshibka send_file

### ISSUE THREAD

**Issue by SunKat1** [TihonV/singleclickuvnc#2]
`f = io.BytesIO(batch.encode('cp1251'))
    return send_file(
        f,
        attachment_filename='runner.bat',
        mimetype='application/bat',
        as_attachment=True
    )

![_2017-09-01_09-29-54](https://user-images.githubusercontent.com/30462664/29957817-3189f3cc-8ef8-11e7-96e5-56f4b5e18f52.png)
`

**Comment by ityshchenko** [comment]
Добавь stacktrace.

**Comment by TihonV** [comment]
f = io.BytesIO(batch.encode('cp1251')) return send_file( f, attachment_filename='runner.bat', mimetype='application/bat', as_attachment=True )

![2017-08-16 14-25-30](https://user-images.githubusercontent.com/5057658/29958003-3ce6f0fc-8ef9-11e7-9bc1-e760a57b5e78.png)

**Comment by SunKat1** [comment]
где тут трабл с отступом?

![image](https://user-images.githubusercontent.com/30462664/29958588-2270ac4c-8efc-11e7-9e9e-c11b1cab57db.png)

**Comment by ityshchenko** [comment]
Удали метод "ini"

**Comment by ityshchenko** [comment]
Fixing in mg #3
